name: phyplan
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.12
  - pip=22.3.1
  - numpy=1.21.6
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - pandas=1.3.5
  - matplotlib=3.5.3
  - joblib
  - tqdm
  - cudatoolkit=11.1 
  - torchvision
  - torchaudio
  - tensorboard
  - mkl
  - llvm-openmp
  - ffmpeg
  - freetype
  - libprotobuf
  - protobuf=3.19.6
  - requests
  - urllib3
  - pyyaml
  - cryptography
  - pyopenssl
  - pyqt
  - bullet
  - pybullet
  - flask
  - jinja2
  - typing_extensions=4.4.0
  - pip:
      - torch==1.8.1+cu101
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - transformers==4.30.2
      - timm==0.9.10
      - huggingface-hub==0.16.4
      - safetensors==0.4.0
      - mujoco==2.3.6
      - dm-control==1.0.13
      - dm-env==1.6
      - dm-tree==0.1.8
      - isaacgym
      - groundingdino
      - trimesh
      - urdfpy
      - transforms3d
      - meshcat
      - meshzoo
      - opencv-python-headless
      - imageio
      - imageio-ffmpeg
      - pillow
      - pycocotools
      - black
      - yapf
      - rich
      - ipython
      - ipykernel
